version: "3"
services:
  app:
    image: ${AZR_IMAGE}
    build: .
    depends_on:
      - postgres
    ports:
      - ${EX_PORT}:${EX_PORT}

  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - ${WEBAPP_STORAGE_HOME}/database/seed.sql:/docker-entrypoint-initdb.d/init.sql
      - ${WEBAPP_STORAGE_HOME}/pg-data:/var/lib/postgresql
  
