version: "3"
services:
  app:
    image: benju26/node
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./server/models/questions.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg-data:/var/lib/postgresql
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 5050:80
  #   environment: 
  #     PGADMIN_DEFAULT_EMAIL: admin
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
